/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CompiledGraphqlSourceListerExpansion allows custom methods to be added to
// CompiledGraphqlSourceLister.
type CompiledGraphqlSourceListerExpansion interface{}

// CompiledGraphqlSourceNamespaceListerExpansion allows custom methods to be added to
// CompiledGraphqlSourceNamespaceLister.
type CompiledGraphqlSourceNamespaceListerExpansion interface{}

// GraphqlSourceListerExpansion allows custom methods to be added to
// GraphqlSourceLister.
type GraphqlSourceListerExpansion interface{}

// GraphqlSourceNamespaceListerExpansion allows custom methods to be added to
// GraphqlSourceNamespaceLister.
type GraphqlSourceNamespaceListerExpansion interface{}

// JwtHSASecretListerExpansion allows custom methods to be added to
// JwtHSASecretLister.
type JwtHSASecretListerExpansion interface{}

// JwtHSASecretNamespaceListerExpansion allows custom methods to be added to
// JwtHSASecretNamespaceLister.
type JwtHSASecretNamespaceListerExpansion interface{}

// OPAPolicyListerExpansion allows custom methods to be added to
// OPAPolicyLister.
type OPAPolicyListerExpansion interface{}

// OPAPolicyNamespaceListerExpansion allows custom methods to be added to
// OPAPolicyNamespaceLister.
type OPAPolicyNamespaceListerExpansion interface{}

// OpenAPISourceListerExpansion allows custom methods to be added to
// OpenAPISourceLister.
type OpenAPISourceListerExpansion interface{}

// OpenAPISourceNamespaceListerExpansion allows custom methods to be added to
// OpenAPISourceNamespaceLister.
type OpenAPISourceNamespaceListerExpansion interface{}

// PubsubChannelListerExpansion allows custom methods to be added to
// PubsubChannelLister.
type PubsubChannelListerExpansion interface{}

// PubsubChannelNamespaceListerExpansion allows custom methods to be added to
// PubsubChannelNamespaceLister.
type PubsubChannelNamespaceListerExpansion interface{}
