{{ if .Values.dbEvents.enabled }}
#############################################################################################
############################### Service Account and Roles  ##################################
#############################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
 name: dbevents
 namespace: space-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: dbevents
 namespace: space-cloud
rules:
 - apiGroups: [""]
   resources: ["configmaps", "secrets"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: dbevents
 namespace: space-cloud
subjects:
 - kind: ServiceAccount
   name: dbevents # Name is case sensitive
   namespace: space-cloud
roleRef:
 kind: ClusterRole
 name: dbevents
 apiGroup: rbac.authorization.k8s.io
---
#############################################################################################
##################################### Kubernetes config  ####################################
#############################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: dbevents
 name: dbevents
 namespace: space-cloud
spec:
 selector:
   matchLabels:
     app: dbevents
 replicas: 1
 template:
   metadata:
     labels:
       app: dbevents
   spec:
     serviceAccountName: dbevents
     containers:
       - name: dbevents
         image: "{{ .Values.dbEvents.image.name }}:{{ .Values.dbEvents.image.version }}"
         imagePullPolicy: "{{ .Values.dbEvents.image.pullPolicy }}"
         env:
           - name: "SC_ADMIN_SECRET"
             value: "{{ .Values.admin.secret }}"
           - name: "GATEWAY_URL"
             value: "gateway.space-cloud.svc.cluster.local:4122"
           - name: "STORAGE_TYPE"
             value: "k8s"
         resources:
           limits:
             memory: "{{ .Values.dbEvents.resources.limits.memory }}"
             cpu: "{{ .Values.dbEvents.resources.limits.cpu }}"
           requests:
             cpu: "{{ .Values.dbEvents.resources.requests.cpu }}"
             memory: "{{ .Values.dbEvents.resources.requests.memory }}"
     terminationGracePeriodSeconds: 300
{{ end }}