apiVersion: v3
name: mongo
version: 0.1.0 # Chart version
description: NoSQL document-oriented database that stores JSON-like documents with dynamic schemas, simplifying the integration of data in content-driven applications.
type: application
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
home: https://spaceuptech.com/
sources:
  - https://github.com/spaceuptech/space-cloud/tree/master/install-manifests/helm/mongo

