# Default values for mongo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

credentials:
  password: pass
  username: user

# name used for creating kubernetes resources
name: "mongo"

# Storage size of mysql
size: "10Gi"

image:
  name: "mongo"
  tag: "4.4"
  pullPolicy: IfNotPresent # IfNotPresent | Always

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"