//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSecret) DeepCopyInto(out *AuthSecret) {
	*out = *in
	if in.AllowedAudiences != nil {
		in, out := &in.AllowedAudiences, &out.AllowedAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedIssuers != nil {
		in, out := &in.AllowedIssuers, &out.AllowedIssuers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSecret.
func (in *AuthSecret) DeepCopy() *AuthSecret {
	if in == nil {
		return nil
	}
	out := new(AuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelOptions) DeepCopyInto(out *ChannelOptions) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]HTTPPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelOptions.
func (in *ChannelOptions) DeepCopy() *ChannelOptions {
	if in == nil {
		return nil
	}
	out := new(ChannelOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelSchema) DeepCopyInto(out *ChannelSchema) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new(ChannelSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]*ChannelSchema, len(*in))
		for key, val := range *in {
			var outVal *ChannelSchema
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(ChannelSchema)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalProperties != nil {
		in, out := &in.AdditionalProperties, &out.AdditionalProperties
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelSchema.
func (in *ChannelSchema) DeepCopy() *ChannelSchema {
	if in == nil {
		return nil
	}
	out := new(ChannelSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledGraphqlSource) DeepCopyInto(out *CompiledGraphqlSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledGraphqlSource.
func (in *CompiledGraphqlSource) DeepCopy() *CompiledGraphqlSource {
	if in == nil {
		return nil
	}
	out := new(CompiledGraphqlSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledGraphqlSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledGraphqlSourceList) DeepCopyInto(out *CompiledGraphqlSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompiledGraphqlSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledGraphqlSourceList.
func (in *CompiledGraphqlSourceList) DeepCopy() *CompiledGraphqlSourceList {
	if in == nil {
		return nil
	}
	out := new(CompiledGraphqlSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompiledGraphqlSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledGraphqlSourceSpec) DeepCopyInto(out *CompiledGraphqlSourceSpec) {
	*out = *in
	in.Graphql.DeepCopyInto(&out.Graphql)
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPOptions)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]HTTPPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledGraphqlSourceSpec.
func (in *CompiledGraphqlSourceSpec) DeepCopy() *CompiledGraphqlSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CompiledGraphqlSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledGraphqlSourceStatus) DeepCopyInto(out *CompiledGraphqlSourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledGraphqlSourceStatus.
func (in *CompiledGraphqlSourceStatus) DeepCopy() *CompiledGraphqlSourceStatus {
	if in == nil {
		return nil
	}
	out := new(CompiledGraphqlSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvRef) DeepCopyInto(out *EnvRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvRef.
func (in *EnvRef) DeepCopy() *EnvRef {
	if in == nil {
		return nil
	}
	out := new(EnvRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphqlQuery) DeepCopyInto(out *GraphqlQuery) {
	*out = *in
	in.DefaultVariables.DeepCopyInto(&out.DefaultVariables)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphqlQuery.
func (in *GraphqlQuery) DeepCopy() *GraphqlQuery {
	if in == nil {
		return nil
	}
	out := new(GraphqlQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphqlSource) DeepCopyInto(out *GraphqlSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphqlSource.
func (in *GraphqlSource) DeepCopy() *GraphqlSource {
	if in == nil {
		return nil
	}
	out := new(GraphqlSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphqlSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphqlSourceList) DeepCopyInto(out *GraphqlSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphqlSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphqlSourceList.
func (in *GraphqlSourceList) DeepCopy() *GraphqlSourceList {
	if in == nil {
		return nil
	}
	out := new(GraphqlSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphqlSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphqlSourceSpec) DeepCopyInto(out *GraphqlSourceSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(HTTPSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphqlSourceSpec.
func (in *GraphqlSourceSpec) DeepCopy() *GraphqlSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GraphqlSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphqlSourceStatus) DeepCopyInto(out *GraphqlSourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphqlSourceStatus.
func (in *GraphqlSourceStatus) DeepCopy() *GraphqlSourceStatus {
	if in == nil {
		return nil
	}
	out := new(GraphqlSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPOptions) DeepCopyInto(out *HTTPOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPOptions.
func (in *HTTPOptions) DeepCopy() *HTTPOptions {
	if in == nil {
		return nil
	}
	out := new(HTTPOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPlugin) DeepCopyInto(out *HTTPPlugin) {
	*out = *in
	in.Params.DeepCopyInto(&out.Params)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPlugin.
func (in *HTTPPlugin) DeepCopy() *HTTPPlugin {
	if in == nil {
		return nil
	}
	out := new(HTTPPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSource) DeepCopyInto(out *HTTPSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSource.
func (in *HTTPSource) DeepCopy() *HTTPSource {
	if in == nil {
		return nil
	}
	out := new(HTTPSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtHSASecret) DeepCopyInto(out *JwtHSASecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtHSASecret.
func (in *JwtHSASecret) DeepCopy() *JwtHSASecret {
	if in == nil {
		return nil
	}
	out := new(JwtHSASecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JwtHSASecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtHSASecretList) DeepCopyInto(out *JwtHSASecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JwtHSASecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtHSASecretList.
func (in *JwtHSASecretList) DeepCopy() *JwtHSASecretList {
	if in == nil {
		return nil
	}
	out := new(JwtHSASecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JwtHSASecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtHSASecretSpec) DeepCopyInto(out *JwtHSASecretSpec) {
	*out = *in
	in.AuthSecret.DeepCopyInto(&out.AuthSecret)
	in.Secret.DeepCopyInto(&out.Secret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtHSASecretSpec.
func (in *JwtHSASecretSpec) DeepCopy() *JwtHSASecretSpec {
	if in == nil {
		return nil
	}
	out := new(JwtHSASecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtHSASecretStatus) DeepCopyInto(out *JwtHSASecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtHSASecretStatus.
func (in *JwtHSASecretStatus) DeepCopy() *JwtHSASecretStatus {
	if in == nil {
		return nil
	}
	out := new(JwtHSASecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtRSASecret) DeepCopyInto(out *JwtRSASecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtRSASecret.
func (in *JwtRSASecret) DeepCopy() *JwtRSASecret {
	if in == nil {
		return nil
	}
	out := new(JwtRSASecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JwtRSASecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtRSASecretList) DeepCopyInto(out *JwtRSASecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JwtRSASecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtRSASecretList.
func (in *JwtRSASecretList) DeepCopy() *JwtRSASecretList {
	if in == nil {
		return nil
	}
	out := new(JwtRSASecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JwtRSASecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtRSASecretSpec) DeepCopyInto(out *JwtRSASecretSpec) {
	*out = *in
	in.AuthSecret.DeepCopyInto(&out.AuthSecret)
	in.PublicKey.DeepCopyInto(&out.PublicKey)
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(SecretSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtRSASecretSpec.
func (in *JwtRSASecretSpec) DeepCopy() *JwtRSASecretSpec {
	if in == nil {
		return nil
	}
	out := new(JwtRSASecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtRSASecretStatus) DeepCopyInto(out *JwtRSASecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtRSASecretStatus.
func (in *JwtRSASecretStatus) DeepCopy() *JwtRSASecretStatus {
	if in == nil {
		return nil
	}
	out := new(JwtRSASecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAPolicy) DeepCopyInto(out *OPAPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAPolicy.
func (in *OPAPolicy) DeepCopy() *OPAPolicy {
	if in == nil {
		return nil
	}
	out := new(OPAPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPAPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAPolicyList) DeepCopyInto(out *OPAPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OPAPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAPolicyList.
func (in *OPAPolicyList) DeepCopy() *OPAPolicyList {
	if in == nil {
		return nil
	}
	out := new(OPAPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPAPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAPolicySpec) DeepCopyInto(out *OPAPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAPolicySpec.
func (in *OPAPolicySpec) DeepCopy() *OPAPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OPAPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPAPolicyStatus) DeepCopyInto(out *OPAPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPAPolicyStatus.
func (in *OPAPolicyStatus) DeepCopy() *OPAPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(OPAPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPISource) DeepCopyInto(out *OpenAPISource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPISource.
func (in *OpenAPISource) DeepCopy() *OpenAPISource {
	if in == nil {
		return nil
	}
	out := new(OpenAPISource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenAPISource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPISourceList) DeepCopyInto(out *OpenAPISourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenAPISource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPISourceList.
func (in *OpenAPISourceList) DeepCopy() *OpenAPISourceList {
	if in == nil {
		return nil
	}
	out := new(OpenAPISourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenAPISourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPISourceSpec) DeepCopyInto(out *OpenAPISourceSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(HTTPSource)
		**out = **in
	}
	in.OpenAPI.DeepCopyInto(&out.OpenAPI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPISourceSpec.
func (in *OpenAPISourceSpec) DeepCopy() *OpenAPISourceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenAPISourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPISourceStatus) DeepCopyInto(out *OpenAPISourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPISourceStatus.
func (in *OpenAPISourceStatus) DeepCopy() *OpenAPISourceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenAPISourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAPISpec) DeepCopyInto(out *OpenAPISpec) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(HTTPOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAPISpec.
func (in *OpenAPISpec) DeepCopy() *OpenAPISpec {
	if in == nil {
		return nil
	}
	out := new(OpenAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubsubChannel) DeepCopyInto(out *PubsubChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubsubChannel.
func (in *PubsubChannel) DeepCopy() *PubsubChannel {
	if in == nil {
		return nil
	}
	out := new(PubsubChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PubsubChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubsubChannelList) DeepCopyInto(out *PubsubChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PubsubChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubsubChannelList.
func (in *PubsubChannelList) DeepCopy() *PubsubChannelList {
	if in == nil {
		return nil
	}
	out := new(PubsubChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PubsubChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubsubChannelSpec) DeepCopyInto(out *PubsubChannelSpec) {
	*out = *in
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = new(ChannelSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.ProducerOptions != nil {
		in, out := &in.ProducerOptions, &out.ProducerOptions
		*out = new(ChannelOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsumerOptions != nil {
		in, out := &in.ConsumerOptions, &out.ConsumerOptions
		*out = new(ChannelOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubsubChannelSpec.
func (in *PubsubChannelSpec) DeepCopy() *PubsubChannelSpec {
	if in == nil {
		return nil
	}
	out := new(PubsubChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PubsubChannelStatus) DeepCopyInto(out *PubsubChannelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PubsubChannelStatus.
func (in *PubsubChannelStatus) DeepCopy() *PubsubChannelStatus {
	if in == nil {
		return nil
	}
	out := new(PubsubChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSource) DeepCopyInto(out *SecretSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.EnvRef != nil {
		in, out := &in.EnvRef, &out.EnvRef
		*out = new(EnvRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSource.
func (in *SecretSource) DeepCopy() *SecretSource {
	if in == nil {
		return nil
	}
	out := new(SecretSource)
	in.DeepCopyInto(out)
	return out
}
