package config

// Integrations describes all the integrations registered in the cluster
type Integrations []IntegrationConfig

// IntegrationConfig describes the configuration of a single integration
type IntegrationConfig struct {
	ID                string                  `json:"id" yaml:"id"`
	Key               string                  `json:"key" yaml:"key"`
	Version           string                  `json:"version" yaml:"version"`
	Level             int                     `json:"level" yaml:"level"`
	ConfigPermissions []IntegrationPermission `json:"configPermissions" yaml:"configPermissions"`
	APIPermissions    []IntegrationPermission `json:"apiPermissions" yaml:"apiPermissions"`
	Deployments       []interface{}           `json:"deployments" yaml:"deployments"`
	SecretSource      string                  `json:"secretSource" yaml:"secretSource"`
	App               string                  `json:"app" yaml:"app"`
	Hooks             []IntegrationHook       `json:"hooks" yaml:"hooks"`
}

// IntegrationHook describes the config for a integration hook
type IntegrationHook struct {
	ID         string     `json:"id" yaml:"id"`
	Resource   []string   `json:"resources" yaml:"resources"`
	Verbs      []string   `json:"verbs" yaml:"verbs"`
	URL        string     `json:"url" yaml:"url"`
	Attributes Attributes `json:"attributes" yaml:"attributes"`
}

// IntegrationPermission describes a single permission object
type IntegrationPermission struct {
	ID         string     `json:"id" yaml:"id"`
	Resources  []string   `json:"resources" yaml:"resources"`   // Eg. db-schema, eventing-trigger, db-api
	Attributes Attributes `json:"attributes" yaml:"attributes"` // Extra attributes like db and col go here
	Verbs      []string   `json:"verbs" yaml:"verbs"`           // Eg. read, write, hook
}

// Attributes describes the attributes of an integration resource.
type Attributes map[string][]string

// IntegrationAuthResponse
type IntegrationAuthResponse interface {
	// CheckResponse signifies whether the response of the integration module needs to be checked or now.
	// If the value `true` is returned, this means the integration moduke intends to control the response of
	// the auth request.
	CheckResponse() bool

	// The error to be sent back. This error is generated by the integration module. An error can be present when
	// an integration is trying to configure a resource which it does not have access to.
	Error() error
}
