// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Document             []byte   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CreateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *CreateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ReadRequest struct {
	Find                 []byte       `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string       `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Options              *ReadOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Meta                 *Meta        `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *ReadRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ReadRequest) GetOptions() *ReadOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ReadRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ReadOptions struct {
	Select               map[string]int32 `protobuf:"bytes,1,rep,name=select,proto3" json:"select,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Sort                 map[string]int32 `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Skip                 int64            `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64            `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Distinct             string           `protobuf:"bytes,5,opt,name=distinct,proto3" json:"distinct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadOptions) Reset()         { *m = ReadOptions{} }
func (m *ReadOptions) String() string { return proto.CompactTextString(m) }
func (*ReadOptions) ProtoMessage()    {}
func (*ReadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ReadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOptions.Unmarshal(m, b)
}
func (m *ReadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOptions.Marshal(b, m, deterministic)
}
func (m *ReadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOptions.Merge(m, src)
}
func (m *ReadOptions) XXX_Size() int {
	return xxx_messageInfo_ReadOptions.Size(m)
}
func (m *ReadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOptions proto.InternalMessageInfo

func (m *ReadOptions) GetSelect() map[string]int32 {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ReadOptions) GetSort() map[string]int32 {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ReadOptions) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ReadOptions) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadOptions) GetDistinct() string {
	if m != nil {
		return m.Distinct
	}
	return ""
}

type UpdateRequest struct {
	Find                 []byte   `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Update               []byte   `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *UpdateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *UpdateRequest) GetUpdate() []byte {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type DeleteRequest struct {
	Find                 []byte   `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *DeleteRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *DeleteRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AggregateRequest struct {
	Pipeline             []byte   `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregateRequest) Reset()         { *m = AggregateRequest{} }
func (m *AggregateRequest) String() string { return proto.CompactTextString(m) }
func (*AggregateRequest) ProtoMessage()    {}
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *AggregateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregateRequest.Unmarshal(m, b)
}
func (m *AggregateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregateRequest.Marshal(b, m, deterministic)
}
func (m *AggregateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateRequest.Merge(m, src)
}
func (m *AggregateRequest) XXX_Size() int {
	return xxx_messageInfo_AggregateRequest.Size(m)
}
func (m *AggregateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateRequest proto.InternalMessageInfo

func (m *AggregateRequest) GetPipeline() []byte {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *AggregateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *AggregateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type Meta struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	DbType               string   `protobuf:"bytes,2,opt,name=dbType,proto3" json:"dbType,omitempty"`
	Col                  string   `protobuf:"bytes,3,opt,name=col,proto3" json:"col,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Meta) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *Meta) GetCol() string {
	if m != nil {
		return m.Col
	}
	return ""
}

func (m *Meta) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AllRequest struct {
	Col                  string   `protobuf:"bytes,1,opt,name=col,proto3" json:"col,omitempty"`
	Document             []byte   `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Find                 []byte   `protobuf:"bytes,4,opt,name=find,proto3" json:"find,omitempty"`
	Update               []byte   `protobuf:"bytes,5,opt,name=update,proto3" json:"update,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRequest) Reset()         { *m = AllRequest{} }
func (m *AllRequest) String() string { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()    {}
func (*AllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *AllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRequest.Unmarshal(m, b)
}
func (m *AllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRequest.Marshal(b, m, deterministic)
}
func (m *AllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRequest.Merge(m, src)
}
func (m *AllRequest) XXX_Size() int {
	return xxx_messageInfo_AllRequest.Size(m)
}
func (m *AllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllRequest proto.InternalMessageInfo

func (m *AllRequest) GetCol() string {
	if m != nil {
		return m.Col
	}
	return ""
}

func (m *AllRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *AllRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *AllRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *AllRequest) GetUpdate() []byte {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *AllRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type BatchRequest struct {
	Batchrequest         []*AllRequest `protobuf:"bytes,1,rep,name=batchrequest,proto3" json:"batchrequest,omitempty"`
	Meta                 *Meta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BatchRequest) Reset()         { *m = BatchRequest{} }
func (m *BatchRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()    {}
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *BatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequest.Unmarshal(m, b)
}
func (m *BatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequest.Marshal(b, m, deterministic)
}
func (m *BatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequest.Merge(m, src)
}
func (m *BatchRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRequest.Size(m)
}
func (m *BatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequest proto.InternalMessageInfo

func (m *BatchRequest) GetBatchrequest() []*AllRequest {
	if m != nil {
		return m.Batchrequest
	}
	return nil
}

func (m *BatchRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type FunctionsRequest struct {
	Params               []byte   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Project              string   `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionsRequest) Reset()         { *m = FunctionsRequest{} }
func (m *FunctionsRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionsRequest) ProtoMessage()    {}
func (*FunctionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *FunctionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionsRequest.Unmarshal(m, b)
}
func (m *FunctionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionsRequest.Marshal(b, m, deterministic)
}
func (m *FunctionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionsRequest.Merge(m, src)
}
func (m *FunctionsRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionsRequest.Size(m)
}
func (m *FunctionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionsRequest proto.InternalMessageInfo

func (m *FunctionsRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FunctionsRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *FunctionsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *FunctionsRequest) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *FunctionsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FunctionsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type FunctionsPayload struct {
	Auth                 []byte   `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Project              string   `protobuf:"bytes,8,opt,name=project,proto3" json:"project,omitempty"`
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionsPayload) Reset()         { *m = FunctionsPayload{} }
func (m *FunctionsPayload) String() string { return proto.CompactTextString(m) }
func (*FunctionsPayload) ProtoMessage()    {}
func (*FunctionsPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *FunctionsPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionsPayload.Unmarshal(m, b)
}
func (m *FunctionsPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionsPayload.Marshal(b, m, deterministic)
}
func (m *FunctionsPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionsPayload.Merge(m, src)
}
func (m *FunctionsPayload) XXX_Size() int {
	return xxx_messageInfo_FunctionsPayload.Size(m)
}
func (m *FunctionsPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionsPayload.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionsPayload proto.InternalMessageInfo

func (m *FunctionsPayload) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *FunctionsPayload) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FunctionsPayload) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *FunctionsPayload) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *FunctionsPayload) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FunctionsPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FunctionsPayload) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FunctionsPayload) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *FunctionsPayload) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FeedData struct {
	QueryId              string   `protobuf:"bytes,1,opt,name=queryId,proto3" json:"queryId,omitempty"`
	DocId                string   `protobuf:"bytes,2,opt,name=docId,proto3" json:"docId,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	DbType               string   `protobuf:"bytes,5,opt,name=dbType,proto3" json:"dbType,omitempty"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeStamp            int64    `protobuf:"varint,7,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedData) Reset()         { *m = FeedData{} }
func (m *FeedData) String() string { return proto.CompactTextString(m) }
func (*FeedData) ProtoMessage()    {}
func (*FeedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{12}
}

func (m *FeedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedData.Unmarshal(m, b)
}
func (m *FeedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedData.Marshal(b, m, deterministic)
}
func (m *FeedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedData.Merge(m, src)
}
func (m *FeedData) XXX_Size() int {
	return xxx_messageInfo_FeedData.Size(m)
}
func (m *FeedData) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedData.DiscardUnknown(m)
}

var xxx_messageInfo_FeedData proto.InternalMessageInfo

func (m *FeedData) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *FeedData) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *FeedData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FeedData) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *FeedData) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *FeedData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FeedData) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type RealTimeRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DbType               string   `protobuf:"bytes,2,opt,name=dbType,proto3" json:"dbType,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Where                []byte   `protobuf:"bytes,7,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealTimeRequest) Reset()         { *m = RealTimeRequest{} }
func (m *RealTimeRequest) String() string { return proto.CompactTextString(m) }
func (*RealTimeRequest) ProtoMessage()    {}
func (*RealTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{13}
}

func (m *RealTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeRequest.Unmarshal(m, b)
}
func (m *RealTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeRequest.Marshal(b, m, deterministic)
}
func (m *RealTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeRequest.Merge(m, src)
}
func (m *RealTimeRequest) XXX_Size() int {
	return xxx_messageInfo_RealTimeRequest.Size(m)
}
func (m *RealTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeRequest proto.InternalMessageInfo

func (m *RealTimeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RealTimeRequest) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *RealTimeRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RealTimeRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *RealTimeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RealTimeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RealTimeRequest) GetWhere() []byte {
	if m != nil {
		return m.Where
	}
	return nil
}

type RealTimeResponse struct {
	Group                string      `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Id                   string      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ack                  bool        `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Error                string      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	FeedData             []*FeedData `protobuf:"bytes,5,rep,name=feedData,proto3" json:"feedData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RealTimeResponse) Reset()         { *m = RealTimeResponse{} }
func (m *RealTimeResponse) String() string { return proto.CompactTextString(m) }
func (*RealTimeResponse) ProtoMessage()    {}
func (*RealTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{14}
}

func (m *RealTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeResponse.Unmarshal(m, b)
}
func (m *RealTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeResponse.Marshal(b, m, deterministic)
}
func (m *RealTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeResponse.Merge(m, src)
}
func (m *RealTimeResponse) XXX_Size() int {
	return xxx_messageInfo_RealTimeResponse.Size(m)
}
func (m *RealTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeResponse proto.InternalMessageInfo

func (m *RealTimeResponse) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *RealTimeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RealTimeResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func (m *RealTimeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RealTimeResponse) GetFeedData() []*FeedData {
	if m != nil {
		return m.FeedData
	}
	return nil
}

type ProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{15}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProfileRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ProfilesRequest struct {
	Meta                 *Meta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilesRequest) Reset()         { *m = ProfilesRequest{} }
func (m *ProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ProfilesRequest) ProtoMessage()    {}
func (*ProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{16}
}

func (m *ProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilesRequest.Unmarshal(m, b)
}
func (m *ProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilesRequest.Merge(m, src)
}
func (m *ProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ProfilesRequest.Size(m)
}
func (m *ProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilesRequest proto.InternalMessageInfo

func (m *ProfilesRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type EditProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRequest) Reset()         { *m = EditProfileRequest{} }
func (m *EditProfileRequest) String() string { return proto.CompactTextString(m) }
func (*EditProfileRequest) ProtoMessage()    {}
func (*EditProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{17}
}

func (m *EditProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRequest.Unmarshal(m, b)
}
func (m *EditProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRequest.Marshal(b, m, deterministic)
}
func (m *EditProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRequest.Merge(m, src)
}
func (m *EditProfileRequest) XXX_Size() int {
	return xxx_messageInfo_EditProfileRequest.Size(m)
}
func (m *EditProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRequest proto.InternalMessageInfo

func (m *EditProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EditProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditProfileRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EditProfileRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{18}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignInRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{19}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *SignUpRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto.RegisterType((*ReadOptions)(nil), "proto.ReadOptions")
	proto.RegisterMapType((map[string]int32)(nil), "proto.ReadOptions.SelectEntry")
	proto.RegisterMapType((map[string]int32)(nil), "proto.ReadOptions.SortEntry")
	proto.RegisterType((*UpdateRequest)(nil), "proto.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*AggregateRequest)(nil), "proto.AggregateRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Meta)(nil), "proto.Meta")
	proto.RegisterType((*AllRequest)(nil), "proto.AllRequest")
	proto.RegisterType((*BatchRequest)(nil), "proto.BatchRequest")
	proto.RegisterType((*FunctionsRequest)(nil), "proto.FunctionsRequest")
	proto.RegisterType((*FunctionsPayload)(nil), "proto.FunctionsPayload")
	proto.RegisterType((*FeedData)(nil), "proto.FeedData")
	proto.RegisterType((*RealTimeRequest)(nil), "proto.RealTimeRequest")
	proto.RegisterType((*RealTimeResponse)(nil), "proto.RealTimeResponse")
	proto.RegisterType((*ProfileRequest)(nil), "proto.ProfileRequest")
	proto.RegisterType((*ProfilesRequest)(nil), "proto.ProfilesRequest")
	proto.RegisterType((*EditProfileRequest)(nil), "proto.EditProfileRequest")
	proto.RegisterType((*SignInRequest)(nil), "proto.SignInRequest")
	proto.RegisterType((*SignUpRequest)(nil), "proto.SignUpRequest")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 1167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdf, 0x6e, 0xdc, 0xc4,
	0x17, 0xfe, 0xd9, 0x5e, 0x6f, 0x76, 0xcf, 0x6e, 0x9b, 0xfc, 0x86, 0x92, 0x2e, 0xab, 0x8a, 0x46,
	0x7b, 0x15, 0x09, 0x08, 0x6d, 0x4a, 0x29, 0x7f, 0xae, 0x92, 0xb4, 0x95, 0x72, 0x81, 0x88, 0x26,
	0xcd, 0x35, 0x4c, 0xec, 0x49, 0xe2, 0xc6, 0xf6, 0xb8, 0xe3, 0x71, 0xab, 0xf0, 0x02, 0x48, 0x20,
	0xb8, 0xe6, 0x15, 0xe0, 0x0e, 0x89, 0xe7, 0xe1, 0x59, 0xd0, 0xfc, 0xf5, 0x78, 0xb3, 0x9b, 0xa5,
	0xf4, 0x6a, 0xe7, 0xac, 0xe7, 0x9c, 0xef, 0x9c, 0xf3, 0x9d, 0x6f, 0x66, 0x60, 0x5c, 0x53, 0xfe,
	0x9a, 0xf2, 0x9d, 0x8a, 0x33, 0xc1, 0x50, 0xac, 0x7e, 0x66, 0x2f, 0xe1, 0xd6, 0x01, 0xa7, 0x44,
	0x50, 0x4c, 0x5f, 0x35, 0xb4, 0x16, 0x68, 0x0a, 0x83, 0x94, 0x25, 0x4d, 0x41, 0x4b, 0x31, 0x09,
	0xb6, 0x82, 0xed, 0x31, 0x76, 0x36, 0xba, 0x07, 0x43, 0x56, 0x51, 0x4e, 0x44, 0xc6, 0xca, 0x49,
	0xb8, 0x15, 0x6c, 0x0f, 0x71, 0xfb, 0x07, 0xba, 0x0f, 0xbd, 0x82, 0x0a, 0x32, 0x89, 0xb6, 0x82,
	0xed, 0xd1, 0xee, 0x48, 0xe3, 0xec, 0x7c, 0x43, 0x05, 0xc1, 0xea, 0xc3, 0xec, 0xd7, 0x00, 0x46,
	0x98, 0x92, 0xd4, 0x42, 0x21, 0xe8, 0x9d, 0x65, 0x65, 0x6a, 0x60, 0xd4, 0x7a, 0x05, 0xc4, 0xc7,
	0xb0, 0xc6, 0x2a, 0xb9, 0xaa, 0x0d, 0x0a, 0x32, 0x28, 0x32, 0xec, 0xb7, 0xfa, 0x0b, 0xb6, 0x5b,
	0x5c, 0x42, 0xbd, 0x65, 0x09, 0xfd, 0x19, 0xea, 0x84, 0x8c, 0x27, 0xfa, 0x1c, 0xfa, 0x35, 0xcd,
	0x69, 0x22, 0x2b, 0x8f, 0xb6, 0x47, 0xbb, 0x1f, 0x5e, 0x8f, 0xbe, 0x73, 0xac, 0x36, 0x3c, 0x2b,
	0x05, 0xbf, 0xc2, 0x66, 0x37, 0x7a, 0x00, 0xbd, 0x9a, 0x71, 0x31, 0x09, 0x95, 0xd7, 0xbd, 0x45,
	0x5e, 0x8c, 0x1b, 0x1f, 0xb5, 0x53, 0x96, 0x5e, 0x5f, 0x66, 0x95, 0xaa, 0x22, 0xc2, 0x6a, 0x8d,
	0xee, 0x40, 0x9c, 0x67, 0x45, 0x26, 0x54, 0xbe, 0x11, 0xd6, 0x86, 0xe2, 0x23, 0xab, 0x45, 0x56,
	0x26, 0x62, 0x12, 0xab, 0x7e, 0x38, 0x7b, 0xfa, 0x25, 0x8c, 0xbc, 0x74, 0xd0, 0x06, 0x44, 0x97,
	0xf4, 0x4a, 0xb5, 0x73, 0x88, 0xe5, 0x52, 0x86, 0x7c, 0x4d, 0xf2, 0x86, 0xaa, 0x4e, 0xc6, 0x58,
	0x1b, 0x5f, 0x85, 0x5f, 0x04, 0xd3, 0x27, 0x30, 0x74, 0x39, 0xbd, 0x8d, 0xe3, 0xec, 0x07, 0xb8,
	0x75, 0x52, 0xa5, 0xde, 0xc0, 0xbc, 0x3d, 0x8b, 0x9b, 0xd0, 0x6f, 0x54, 0x08, 0x55, 0xfe, 0x18,
	0x1b, 0x6b, 0x35, 0x5f, 0xa7, 0x70, 0xeb, 0x29, 0xcd, 0xe9, 0xbb, 0x60, 0xaf, 0x1c, 0xd2, 0x02,
	0x36, 0xf6, 0xce, 0xcf, 0x39, 0x3d, 0xef, 0x6a, 0xa2, 0xca, 0x2a, 0x9a, 0x67, 0x25, 0xb5, 0x9a,
	0xb0, 0xf6, 0xbb, 0xc2, 0x1d, 0xc1, 0x00, 0xd3, 0xba, 0x62, 0x65, 0x4d, 0x65, 0x5f, 0x6a, 0x41,
	0x44, 0x53, 0x2b, 0x90, 0x18, 0x1b, 0x4b, 0x92, 0x41, 0x39, 0x67, 0xdc, 0x84, 0xd7, 0x86, 0xdc,
	0xcd, 0x69, 0xdd, 0xe4, 0xc2, 0x76, 0x51, 0x5b, 0xb3, 0xef, 0xa1, 0x27, 0xe3, 0xa3, 0x09, 0xac,
	0x55, 0x9c, 0xbd, 0xd4, 0xd3, 0x2c, 0xfd, 0xac, 0x29, 0x3d, 0xd3, 0xd3, 0x17, 0x57, 0x15, 0x35,
	0x01, 0x8d, 0x25, 0xc7, 0x20, 0x61, 0xb9, 0x0a, 0x37, 0xc4, 0x72, 0x29, 0x91, 0x05, 0xbb, 0xa4,
	0xa5, 0xa2, 0x64, 0x88, 0xb5, 0x31, 0xfb, 0x2d, 0x00, 0xd8, 0xcb, 0x73, 0xdb, 0x1d, 0xe3, 0x16,
	0xb4, 0x6e, 0xfe, 0x19, 0x12, 0xde, 0x74, 0x86, 0x44, 0xf3, 0xfd, 0xb2, 0x84, 0xf6, 0x3c, 0x42,
	0xdb, 0x71, 0x89, 0x3b, 0xe3, 0x82, 0xa0, 0x27, 0x64, 0x11, 0x7d, 0x15, 0x44, 0xad, 0x67, 0x67,
	0x30, 0xde, 0x27, 0x22, 0xb9, 0xb0, 0xb9, 0x3d, 0x86, 0xf1, 0xa9, 0xb4, 0xb9, 0xb6, 0x8d, 0xae,
	0xff, 0x6f, 0x78, 0x68, 0x8b, 0xc0, 0x9d, 0x6d, 0x8e, 0xb6, 0x70, 0x19, 0x6d, 0x7f, 0x04, 0xb0,
	0xf1, 0xbc, 0x29, 0x13, 0x7d, 0xe2, 0x18, 0xaf, 0x4d, 0xe8, 0x57, 0x84, 0x93, 0xa2, 0x36, 0x43,
	0x62, 0x2c, 0xc9, 0x84, 0xc8, 0x0a, 0xca, 0x1a, 0xdd, 0x8d, 0x08, 0x5b, 0x53, 0x7e, 0x91, 0x87,
	0x72, 0x96, 0x50, 0xd3, 0x0a, 0x6b, 0xca, 0x16, 0x9e, 0x99, 0xf8, 0xa6, 0xf9, 0xce, 0x6e, 0x59,
	0x89, 0x3d, 0x56, 0x7c, 0xbe, 0xfb, 0x1d, 0xbe, 0x67, 0x7f, 0xfb, 0xc9, 0x1e, 0x91, 0xab, 0x9c,
	0x91, 0x54, 0x76, 0x8f, 0x34, 0xe2, 0xc2, 0x4a, 0x47, 0xae, 0xbd, 0x02, 0xc2, 0xf9, 0x02, 0xfe,
	0x43, 0x9a, 0x96, 0x9f, 0xb8, 0xe5, 0x07, 0xdd, 0x86, 0x30, 0x4b, 0x4d, 0x7e, 0x61, 0x96, 0xb6,
	0xa3, 0xbd, 0xe6, 0x8f, 0xb6, 0x57, 0xca, 0xa0, 0x3b, 0xba, 0xae, 0xf4, 0xa1, 0x3f, 0x90, 0x7f,
	0x05, 0x30, 0x78, 0x4e, 0x69, 0xfa, 0x94, 0xe8, 0xb9, 0x7f, 0xd5, 0x50, 0x7e, 0x75, 0x98, 0xda,
	0xb9, 0x37, 0xa6, 0x74, 0x4e, 0x59, 0x72, 0x98, 0x5a, 0x1d, 0x29, 0xc3, 0xa5, 0x19, 0x79, 0x69,
	0xde, 0x81, 0xf8, 0x9c, 0xb3, 0xa6, 0xb2, 0x73, 0xaf, 0x0c, 0x4f, 0x37, 0x71, 0x47, 0x37, 0x32,
	0x5d, 0xdd, 0x55, 0x55, 0xd9, 0x18, 0x5b, 0x53, 0x0e, 0xbb, 0xa4, 0xfa, 0x58, 0x90, 0xa2, 0x52,
	0x25, 0x46, 0xb8, 0xfd, 0x63, 0xf6, 0x7b, 0x00, 0xeb, 0x98, 0x92, 0xfc, 0x45, 0x56, 0xb8, 0xa3,
	0xc6, 0x15, 0x18, 0xf8, 0xdc, 0x2e, 0x53, 0xac, 0xd7, 0xa8, 0xe8, 0x5a, 0xa3, 0x16, 0x54, 0xf0,
	0x2f, 0x29, 0x79, 0x73, 0x41, 0x39, 0x55, 0xf9, 0x8e, 0xb1, 0x36, 0x66, 0xbf, 0x04, 0xb0, 0xd1,
	0xe6, 0x6a, 0x0e, 0x2c, 0x07, 0x12, 0xf8, 0x20, 0x3a, 0x60, 0xe8, 0x02, 0x6e, 0x40, 0x44, 0x92,
	0x4b, 0x95, 0xe0, 0x00, 0xcb, 0x65, 0xcb, 0x7a, 0xcf, 0x67, 0xfd, 0x23, 0x18, 0x9c, 0x19, 0x12,
	0x27, 0xb1, 0xd2, 0xe9, 0xba, 0x11, 0x9e, 0xe5, 0x16, 0xbb, 0x0d, 0xb3, 0x3d, 0xb8, 0x7d, 0xc4,
	0xd9, 0x59, 0x96, 0xbb, 0xce, 0x69, 0xd8, 0xc0, 0xc1, 0xae, 0xd4, 0xf0, 0x2e, 0xac, 0x9b, 0x10,
	0x4e, 0xc1, 0xd6, 0x27, 0x58, 0xe6, 0xf3, 0x73, 0x00, 0xe8, 0x59, 0x9a, 0x89, 0x15, 0xd8, 0xb2,
	0xc0, 0x82, 0x64, 0xb9, 0x3b, 0xb1, 0xa5, 0x21, 0xbb, 0x5f, 0x92, 0xc2, 0x4d, 0x9a, 0x5c, 0xab,
	0xab, 0x85, 0xd4, 0xf5, 0x1b, 0xc6, 0x53, 0x2b, 0x20, 0x6b, 0xbb, 0x6c, 0xe2, 0x1b, 0xee, 0xc3,
	0xe3, 0xec, 0xbc, 0x3c, 0x2c, 0xbd, 0xe9, 0xd1, 0xb8, 0x81, 0x8f, 0xeb, 0x63, 0x84, 0x4b, 0x30,
	0x96, 0x5e, 0x50, 0x3f, 0x05, 0x1a, 0xe4, 0xa4, 0xba, 0x19, 0xc4, 0x16, 0x17, 0x2e, 0x29, 0x2e,
	0x9a, 0x03, 0x46, 0xd0, 0xe3, 0x2c, 0xa7, 0xa6, 0x68, 0xb5, 0x5e, 0x59, 0xf0, 0xee, 0x8f, 0x7d,
	0x80, 0xe3, 0x8a, 0x24, 0xf4, 0x20, 0x67, 0x4d, 0x8a, 0x1e, 0x42, 0x5f, 0x3f, 0x5e, 0xd1, 0x1d,
	0xb3, 0xb7, 0xf3, 0x96, 0x9d, 0xae, 0xbb, 0x97, 0x98, 0x1e, 0xd8, 0xd9, 0xff, 0xd0, 0x27, 0xd0,
	0x93, 0xef, 0x32, 0xe4, 0x3f, 0x1c, 0x6f, 0xd8, 0xfe, 0x10, 0xfa, 0xfa, 0xb5, 0xe3, 0x10, 0x3a,
	0x8f, 0x9f, 0x25, 0x2e, 0xfa, 0x91, 0xe2, 0x5c, 0x3a, 0x6f, 0x96, 0x45, 0x2e, 0x4f, 0x60, 0xe8,
	0xde, 0x1c, 0xe8, 0xae, 0xbd, 0x9c, 0xe6, 0x5e, 0x21, 0x8b, 0x1c, 0x3f, 0x85, 0x58, 0x5d, 0x77,
	0xe8, 0x3d, 0xf3, 0xcd, 0xbf, 0xfc, 0x16, 0x39, 0xec, 0x42, 0xef, 0x80, 0xe4, 0xb9, 0x03, 0x99,
	0xbf, 0xc3, 0x16, 0xf9, 0xec, 0xc9, 0x27, 0x8a, 0x56, 0x3e, 0xda, 0x6c, 0xdb, 0xe6, 0x1f, 0x5b,
	0xd3, 0xbb, 0xd7, 0xfe, 0xb7, 0xee, 0xdb, 0xc1, 0x83, 0x00, 0xed, 0xc1, 0xda, 0xb1, 0xb9, 0x31,
	0xae, 0x21, 0x9b, 0x0b, 0x69, 0xba, 0xec, 0x83, 0x09, 0xf1, 0x08, 0xd6, 0x8c, 0xe8, 0xd0, 0xfb,
	0x66, 0x67, 0x57, 0x84, 0x8b, 0x52, 0x7f, 0x0c, 0x03, 0x2b, 0x71, 0x97, 0xfa, 0x9c, 0xe6, 0x17,
	0xb9, 0x7d, 0x0d, 0x23, 0x4f, 0xe4, 0xe8, 0x03, 0xb3, 0xe3, 0xba, 0xf0, 0x97, 0xf0, 0xaf, 0x45,
	0xe9, 0xf8, 0xef, 0x68, 0xf4, 0x06, 0x97, 0x93, 0xaa, 0xe3, 0xe2, 0x14, 0xb7, 0xc0, 0x65, 0xff,
	0x33, 0xb8, 0x9f, 0xb0, 0x62, 0xa7, 0x96, 0x62, 0x68, 0x2a, 0x41, 0x93, 0x0b, 0xbd, 0xfe, 0x8e,
	0x54, 0x99, 0xde, 0xbd, 0xbf, 0xde, 0x2a, 0xe5, 0x48, 0xfe, 0x71, 0x14, 0x9c, 0xf6, 0xd5, 0x97,
	0x47, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x94, 0x99, 0xb2, 0x0b, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpaceCloudClient is the client API for SpaceCloud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpaceCloudClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*Response, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*Response, error)
	Call(ctx context.Context, in *FunctionsRequest, opts ...grpc.CallOption) (*Response, error)
	RealTime(ctx context.Context, opts ...grpc.CallOption) (SpaceCloud_RealTimeClient, error)
	Service(ctx context.Context, opts ...grpc.CallOption) (SpaceCloud_ServiceClient, error)
	Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Response, error)
	Profiles(ctx context.Context, in *ProfilesRequest, opts ...grpc.CallOption) (*Response, error)
	EditProfile(ctx context.Context, in *EditProfileRequest, opts ...grpc.CallOption) (*Response, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Response, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*Response, error)
}

type spaceCloudClient struct {
	cc *grpc.ClientConn
}

func NewSpaceCloudClient(cc *grpc.ClientConn) SpaceCloudClient {
	return &spaceCloudClient{cc}
}

func (c *spaceCloudClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Aggregate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Call(ctx context.Context, in *FunctionsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) RealTime(ctx context.Context, opts ...grpc.CallOption) (SpaceCloud_RealTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SpaceCloud_serviceDesc.Streams[0], "/proto.SpaceCloud/RealTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &spaceCloudRealTimeClient{stream}
	return x, nil
}

type SpaceCloud_RealTimeClient interface {
	Send(*RealTimeRequest) error
	Recv() (*RealTimeResponse, error)
	grpc.ClientStream
}

type spaceCloudRealTimeClient struct {
	grpc.ClientStream
}

func (x *spaceCloudRealTimeClient) Send(m *RealTimeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *spaceCloudRealTimeClient) Recv() (*RealTimeResponse, error) {
	m := new(RealTimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *spaceCloudClient) Service(ctx context.Context, opts ...grpc.CallOption) (SpaceCloud_ServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SpaceCloud_serviceDesc.Streams[1], "/proto.SpaceCloud/Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &spaceCloudServiceClient{stream}
	return x, nil
}

type SpaceCloud_ServiceClient interface {
	Send(*FunctionsPayload) error
	Recv() (*FunctionsPayload, error)
	grpc.ClientStream
}

type spaceCloudServiceClient struct {
	grpc.ClientStream
}

func (x *spaceCloudServiceClient) Send(m *FunctionsPayload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *spaceCloudServiceClient) Recv() (*FunctionsPayload, error) {
	m := new(FunctionsPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *spaceCloudClient) Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Profiles(ctx context.Context, in *ProfilesRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/Profiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) EditProfile(ctx context.Context, in *EditProfileRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/EditProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.SpaceCloud/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceCloudServer is the server API for SpaceCloud service.
type SpaceCloudServer interface {
	Create(context.Context, *CreateRequest) (*Response, error)
	Read(context.Context, *ReadRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*Response, error)
	Delete(context.Context, *DeleteRequest) (*Response, error)
	Aggregate(context.Context, *AggregateRequest) (*Response, error)
	Batch(context.Context, *BatchRequest) (*Response, error)
	Call(context.Context, *FunctionsRequest) (*Response, error)
	RealTime(SpaceCloud_RealTimeServer) error
	Service(SpaceCloud_ServiceServer) error
	Profile(context.Context, *ProfileRequest) (*Response, error)
	Profiles(context.Context, *ProfilesRequest) (*Response, error)
	EditProfile(context.Context, *EditProfileRequest) (*Response, error)
	SignIn(context.Context, *SignInRequest) (*Response, error)
	SignUp(context.Context, *SignUpRequest) (*Response, error)
}

func RegisterSpaceCloudServer(s *grpc.Server, srv SpaceCloudServer) {
	s.RegisterService(&_SpaceCloud_serviceDesc, srv)
}

func _SpaceCloud_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Aggregate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Aggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Batch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Batch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Call(ctx, req.(*FunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_RealTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpaceCloudServer).RealTime(&spaceCloudRealTimeServer{stream})
}

type SpaceCloud_RealTimeServer interface {
	Send(*RealTimeResponse) error
	Recv() (*RealTimeRequest, error)
	grpc.ServerStream
}

type spaceCloudRealTimeServer struct {
	grpc.ServerStream
}

func (x *spaceCloudRealTimeServer) Send(m *RealTimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *spaceCloudRealTimeServer) Recv() (*RealTimeRequest, error) {
	m := new(RealTimeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SpaceCloud_Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpaceCloudServer).Service(&spaceCloudServiceServer{stream})
}

type SpaceCloud_ServiceServer interface {
	Send(*FunctionsPayload) error
	Recv() (*FunctionsPayload, error)
	grpc.ServerStream
}

type spaceCloudServiceServer struct {
	grpc.ServerStream
}

func (x *spaceCloudServiceServer) Send(m *FunctionsPayload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *spaceCloudServiceServer) Recv() (*FunctionsPayload, error) {
	m := new(FunctionsPayload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SpaceCloud_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Profile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Profiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Profiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/Profiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Profiles(ctx, req.(*ProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_EditProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).EditProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/EditProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).EditProfile(ctx, req.(*EditProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SpaceCloud/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpaceCloud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SpaceCloud",
	HandlerType: (*SpaceCloudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SpaceCloud_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SpaceCloud_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SpaceCloud_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SpaceCloud_Delete_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _SpaceCloud_Aggregate_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _SpaceCloud_Batch_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _SpaceCloud_Call_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _SpaceCloud_Profile_Handler,
		},
		{
			MethodName: "Profiles",
			Handler:    _SpaceCloud_Profiles_Handler,
		},
		{
			MethodName: "EditProfile",
			Handler:    _SpaceCloud_EditProfile_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _SpaceCloud_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _SpaceCloud_SignUp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RealTime",
			Handler:       _SpaceCloud_RealTime_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Service",
			Handler:       _SpaceCloud_Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
