/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCompiledGraphqlSources implements CompiledGraphqlSourceInterface
type FakeCompiledGraphqlSources struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var compiledgraphqlsourcesResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "compiledgraphqlsources"}

var compiledgraphqlsourcesKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "CompiledGraphqlSource"}

// Get takes name of the compiledGraphqlSource, and returns the corresponding compiledGraphqlSource object, and an error if there is any.
func (c *FakeCompiledGraphqlSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CompiledGraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(compiledgraphqlsourcesResource, c.ns, name), &v1alpha1.CompiledGraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CompiledGraphqlSource), err
}

// List takes label and field selectors, and returns the list of CompiledGraphqlSources that match those selectors.
func (c *FakeCompiledGraphqlSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CompiledGraphqlSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(compiledgraphqlsourcesResource, compiledgraphqlsourcesKind, c.ns, opts), &v1alpha1.CompiledGraphqlSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CompiledGraphqlSourceList{ListMeta: obj.(*v1alpha1.CompiledGraphqlSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.CompiledGraphqlSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested compiledGraphqlSources.
func (c *FakeCompiledGraphqlSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(compiledgraphqlsourcesResource, c.ns, opts))

}

// Create takes the representation of a compiledGraphqlSource and creates it.  Returns the server's representation of the compiledGraphqlSource, and an error, if there is any.
func (c *FakeCompiledGraphqlSources) Create(ctx context.Context, compiledGraphqlSource *v1alpha1.CompiledGraphqlSource, opts v1.CreateOptions) (result *v1alpha1.CompiledGraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(compiledgraphqlsourcesResource, c.ns, compiledGraphqlSource), &v1alpha1.CompiledGraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CompiledGraphqlSource), err
}

// Update takes the representation of a compiledGraphqlSource and updates it. Returns the server's representation of the compiledGraphqlSource, and an error, if there is any.
func (c *FakeCompiledGraphqlSources) Update(ctx context.Context, compiledGraphqlSource *v1alpha1.CompiledGraphqlSource, opts v1.UpdateOptions) (result *v1alpha1.CompiledGraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(compiledgraphqlsourcesResource, c.ns, compiledGraphqlSource), &v1alpha1.CompiledGraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CompiledGraphqlSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCompiledGraphqlSources) UpdateStatus(ctx context.Context, compiledGraphqlSource *v1alpha1.CompiledGraphqlSource, opts v1.UpdateOptions) (*v1alpha1.CompiledGraphqlSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(compiledgraphqlsourcesResource, "status", c.ns, compiledGraphqlSource), &v1alpha1.CompiledGraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CompiledGraphqlSource), err
}

// Delete takes name of the compiledGraphqlSource and deletes it. Returns an error if one occurs.
func (c *FakeCompiledGraphqlSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(compiledgraphqlsourcesResource, c.ns, name, opts), &v1alpha1.CompiledGraphqlSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCompiledGraphqlSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(compiledgraphqlsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CompiledGraphqlSourceList{})
	return err
}

// Patch applies the patch and returns the patched compiledGraphqlSource.
func (c *FakeCompiledGraphqlSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CompiledGraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(compiledgraphqlsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CompiledGraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CompiledGraphqlSource), err
}
