/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedisSources implements RedisSourceInterface
type FakeRedisSources struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var redissourcesResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "redissources"}

var redissourcesKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "RedisSource"}

// Get takes name of the redisSource, and returns the corresponding redisSource object, and an error if there is any.
func (c *FakeRedisSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redissourcesResource, c.ns, name), &v1alpha1.RedisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisSource), err
}

// List takes label and field selectors, and returns the list of RedisSources that match those selectors.
func (c *FakeRedisSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedisSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redissourcesResource, redissourcesKind, c.ns, opts), &v1alpha1.RedisSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RedisSourceList{ListMeta: obj.(*v1alpha1.RedisSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RedisSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisSources.
func (c *FakeRedisSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redissourcesResource, c.ns, opts))

}

// Create takes the representation of a redisSource and creates it.  Returns the server's representation of the redisSource, and an error, if there is any.
func (c *FakeRedisSources) Create(ctx context.Context, redisSource *v1alpha1.RedisSource, opts v1.CreateOptions) (result *v1alpha1.RedisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redissourcesResource, c.ns, redisSource), &v1alpha1.RedisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisSource), err
}

// Update takes the representation of a redisSource and updates it. Returns the server's representation of the redisSource, and an error, if there is any.
func (c *FakeRedisSources) Update(ctx context.Context, redisSource *v1alpha1.RedisSource, opts v1.UpdateOptions) (result *v1alpha1.RedisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redissourcesResource, c.ns, redisSource), &v1alpha1.RedisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedisSources) UpdateStatus(ctx context.Context, redisSource *v1alpha1.RedisSource, opts v1.UpdateOptions) (*v1alpha1.RedisSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redissourcesResource, "status", c.ns, redisSource), &v1alpha1.RedisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisSource), err
}

// Delete takes name of the redisSource and deletes it. Returns an error if one occurs.
func (c *FakeRedisSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(redissourcesResource, c.ns, name, opts), &v1alpha1.RedisSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redissourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RedisSourceList{})
	return err
}

// Patch applies the patch and returns the patched redisSource.
func (c *FakeRedisSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redissourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RedisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisSource), err
}
