/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHSASecrets implements HSASecretInterface
type FakeHSASecrets struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var hsasecretsResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "hsasecrets"}

var hsasecretsKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "HSASecret"}

// Get takes name of the hSASecret, and returns the corresponding hSASecret object, and an error if there is any.
func (c *FakeHSASecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HSASecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hsasecretsResource, c.ns, name), &v1alpha1.HSASecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HSASecret), err
}

// List takes label and field selectors, and returns the list of HSASecrets that match those selectors.
func (c *FakeHSASecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HSASecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hsasecretsResource, hsasecretsKind, c.ns, opts), &v1alpha1.HSASecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HSASecretList{ListMeta: obj.(*v1alpha1.HSASecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.HSASecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hSASecrets.
func (c *FakeHSASecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hsasecretsResource, c.ns, opts))

}

// Create takes the representation of a hSASecret and creates it.  Returns the server's representation of the hSASecret, and an error, if there is any.
func (c *FakeHSASecrets) Create(ctx context.Context, hSASecret *v1alpha1.HSASecret, opts v1.CreateOptions) (result *v1alpha1.HSASecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hsasecretsResource, c.ns, hSASecret), &v1alpha1.HSASecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HSASecret), err
}

// Update takes the representation of a hSASecret and updates it. Returns the server's representation of the hSASecret, and an error, if there is any.
func (c *FakeHSASecrets) Update(ctx context.Context, hSASecret *v1alpha1.HSASecret, opts v1.UpdateOptions) (result *v1alpha1.HSASecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hsasecretsResource, c.ns, hSASecret), &v1alpha1.HSASecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HSASecret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHSASecrets) UpdateStatus(ctx context.Context, hSASecret *v1alpha1.HSASecret, opts v1.UpdateOptions) (*v1alpha1.HSASecret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hsasecretsResource, "status", c.ns, hSASecret), &v1alpha1.HSASecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HSASecret), err
}

// Delete takes name of the hSASecret and deletes it. Returns an error if one occurs.
func (c *FakeHSASecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hsasecretsResource, c.ns, name, opts), &v1alpha1.HSASecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHSASecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hsasecretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HSASecretList{})
	return err
}

// Patch applies the patch and returns the patched hSASecret.
func (c *FakeHSASecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HSASecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hsasecretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HSASecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HSASecret), err
}
