/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOpenAPISources implements OpenAPISourceInterface
type FakeOpenAPISources struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var openapisourcesResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "openapisources"}

var openapisourcesKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "OpenAPISource"}

// Get takes name of the openAPISource, and returns the corresponding openAPISource object, and an error if there is any.
func (c *FakeOpenAPISources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OpenAPISource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(openapisourcesResource, c.ns, name), &v1alpha1.OpenAPISource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenAPISource), err
}

// List takes label and field selectors, and returns the list of OpenAPISources that match those selectors.
func (c *FakeOpenAPISources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OpenAPISourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(openapisourcesResource, openapisourcesKind, c.ns, opts), &v1alpha1.OpenAPISourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OpenAPISourceList{ListMeta: obj.(*v1alpha1.OpenAPISourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.OpenAPISourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested openAPISources.
func (c *FakeOpenAPISources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(openapisourcesResource, c.ns, opts))

}

// Create takes the representation of a openAPISource and creates it.  Returns the server's representation of the openAPISource, and an error, if there is any.
func (c *FakeOpenAPISources) Create(ctx context.Context, openAPISource *v1alpha1.OpenAPISource, opts v1.CreateOptions) (result *v1alpha1.OpenAPISource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(openapisourcesResource, c.ns, openAPISource), &v1alpha1.OpenAPISource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenAPISource), err
}

// Update takes the representation of a openAPISource and updates it. Returns the server's representation of the openAPISource, and an error, if there is any.
func (c *FakeOpenAPISources) Update(ctx context.Context, openAPISource *v1alpha1.OpenAPISource, opts v1.UpdateOptions) (result *v1alpha1.OpenAPISource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(openapisourcesResource, c.ns, openAPISource), &v1alpha1.OpenAPISource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenAPISource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOpenAPISources) UpdateStatus(ctx context.Context, openAPISource *v1alpha1.OpenAPISource, opts v1.UpdateOptions) (*v1alpha1.OpenAPISource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(openapisourcesResource, "status", c.ns, openAPISource), &v1alpha1.OpenAPISource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenAPISource), err
}

// Delete takes name of the openAPISource and deletes it. Returns an error if one occurs.
func (c *FakeOpenAPISources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(openapisourcesResource, c.ns, name, opts), &v1alpha1.OpenAPISource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOpenAPISources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(openapisourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OpenAPISourceList{})
	return err
}

// Patch applies the patch and returns the patched openAPISource.
func (c *FakeOpenAPISources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OpenAPISource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(openapisourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OpenAPISource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OpenAPISource), err
}
