/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGraphqlSources implements GraphqlSourceInterface
type FakeGraphqlSources struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var graphqlsourcesResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "graphqlsources"}

var graphqlsourcesKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "GraphqlSource"}

// Get takes name of the graphqlSource, and returns the corresponding graphqlSource object, and an error if there is any.
func (c *FakeGraphqlSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(graphqlsourcesResource, c.ns, name), &v1alpha1.GraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphqlSource), err
}

// List takes label and field selectors, and returns the list of GraphqlSources that match those selectors.
func (c *FakeGraphqlSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GraphqlSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(graphqlsourcesResource, graphqlsourcesKind, c.ns, opts), &v1alpha1.GraphqlSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GraphqlSourceList{ListMeta: obj.(*v1alpha1.GraphqlSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.GraphqlSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested graphqlSources.
func (c *FakeGraphqlSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(graphqlsourcesResource, c.ns, opts))

}

// Create takes the representation of a graphqlSource and creates it.  Returns the server's representation of the graphqlSource, and an error, if there is any.
func (c *FakeGraphqlSources) Create(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.CreateOptions) (result *v1alpha1.GraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(graphqlsourcesResource, c.ns, graphqlSource), &v1alpha1.GraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphqlSource), err
}

// Update takes the representation of a graphqlSource and updates it. Returns the server's representation of the graphqlSource, and an error, if there is any.
func (c *FakeGraphqlSources) Update(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (result *v1alpha1.GraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(graphqlsourcesResource, c.ns, graphqlSource), &v1alpha1.GraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphqlSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGraphqlSources) UpdateStatus(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (*v1alpha1.GraphqlSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(graphqlsourcesResource, "status", c.ns, graphqlSource), &v1alpha1.GraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphqlSource), err
}

// Delete takes name of the graphqlSource and deletes it. Returns an error if one occurs.
func (c *FakeGraphqlSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(graphqlsourcesResource, c.ns, name, opts), &v1alpha1.GraphqlSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGraphqlSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(graphqlsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GraphqlSourceList{})
	return err
}

// Patch applies the patch and returns the patched graphqlSource.
func (c *FakeGraphqlSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GraphqlSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(graphqlsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GraphqlSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GraphqlSource), err
}
