/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOPAPolicies implements OPAPolicyInterface
type FakeOPAPolicies struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var opapoliciesResource = schema.GroupVersionResource{Group: "core.space-cloud.io", Version: "v1alpha1", Resource: "opapolicies"}

var opapoliciesKind = schema.GroupVersionKind{Group: "core.space-cloud.io", Version: "v1alpha1", Kind: "OPAPolicy"}

// Get takes name of the oPAPolicy, and returns the corresponding oPAPolicy object, and an error if there is any.
func (c *FakeOPAPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OPAPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(opapoliciesResource, c.ns, name), &v1alpha1.OPAPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OPAPolicy), err
}

// List takes label and field selectors, and returns the list of OPAPolicies that match those selectors.
func (c *FakeOPAPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OPAPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(opapoliciesResource, opapoliciesKind, c.ns, opts), &v1alpha1.OPAPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OPAPolicyList{ListMeta: obj.(*v1alpha1.OPAPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.OPAPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oPAPolicies.
func (c *FakeOPAPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(opapoliciesResource, c.ns, opts))

}

// Create takes the representation of a oPAPolicy and creates it.  Returns the server's representation of the oPAPolicy, and an error, if there is any.
func (c *FakeOPAPolicies) Create(ctx context.Context, oPAPolicy *v1alpha1.OPAPolicy, opts v1.CreateOptions) (result *v1alpha1.OPAPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(opapoliciesResource, c.ns, oPAPolicy), &v1alpha1.OPAPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OPAPolicy), err
}

// Update takes the representation of a oPAPolicy and updates it. Returns the server's representation of the oPAPolicy, and an error, if there is any.
func (c *FakeOPAPolicies) Update(ctx context.Context, oPAPolicy *v1alpha1.OPAPolicy, opts v1.UpdateOptions) (result *v1alpha1.OPAPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(opapoliciesResource, c.ns, oPAPolicy), &v1alpha1.OPAPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OPAPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOPAPolicies) UpdateStatus(ctx context.Context, oPAPolicy *v1alpha1.OPAPolicy, opts v1.UpdateOptions) (*v1alpha1.OPAPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(opapoliciesResource, "status", c.ns, oPAPolicy), &v1alpha1.OPAPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OPAPolicy), err
}

// Delete takes name of the oPAPolicy and deletes it. Returns an error if one occurs.
func (c *FakeOPAPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(opapoliciesResource, c.ns, name, opts), &v1alpha1.OPAPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOPAPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(opapoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OPAPolicyList{})
	return err
}

// Patch applies the patch and returns the patched oPAPolicy.
func (c *FakeOPAPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OPAPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(opapoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OPAPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OPAPolicy), err
}
