# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

credentials:
  password: my-secret-pw

# Name used for creating kubernetes resources
name: "mysql"

# Storage size of mysql
size: "10Gi"

image:
  name: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

resources:
  memory: 256Mi
  cpu: 200m