/*
Copyright The Space Cloud Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/spacecloud-io/space-cloud/pkg/apis/core/v1alpha1"
	scheme "github.com/spacecloud-io/space-cloud/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GraphqlSourcesGetter has a method to return a GraphqlSourceInterface.
// A group's client should implement this interface.
type GraphqlSourcesGetter interface {
	GraphqlSources(namespace string) GraphqlSourceInterface
}

// GraphqlSourceInterface has methods to work with GraphqlSource resources.
type GraphqlSourceInterface interface {
	Create(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.CreateOptions) (*v1alpha1.GraphqlSource, error)
	Update(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (*v1alpha1.GraphqlSource, error)
	UpdateStatus(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (*v1alpha1.GraphqlSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GraphqlSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GraphqlSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GraphqlSource, err error)
	GraphqlSourceExpansion
}

// graphqlSources implements GraphqlSourceInterface
type graphqlSources struct {
	client rest.Interface
	ns     string
}

// newGraphqlSources returns a GraphqlSources
func newGraphqlSources(c *CoreV1alpha1Client, namespace string) *graphqlSources {
	return &graphqlSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the graphqlSource, and returns the corresponding graphqlSource object, and an error if there is any.
func (c *graphqlSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GraphqlSource, err error) {
	result = &v1alpha1.GraphqlSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("graphqlsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GraphqlSources that match those selectors.
func (c *graphqlSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GraphqlSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GraphqlSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("graphqlsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested graphqlSources.
func (c *graphqlSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("graphqlsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a graphqlSource and creates it.  Returns the server's representation of the graphqlSource, and an error, if there is any.
func (c *graphqlSources) Create(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.CreateOptions) (result *v1alpha1.GraphqlSource, err error) {
	result = &v1alpha1.GraphqlSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("graphqlsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(graphqlSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a graphqlSource and updates it. Returns the server's representation of the graphqlSource, and an error, if there is any.
func (c *graphqlSources) Update(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (result *v1alpha1.GraphqlSource, err error) {
	result = &v1alpha1.GraphqlSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("graphqlsources").
		Name(graphqlSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(graphqlSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *graphqlSources) UpdateStatus(ctx context.Context, graphqlSource *v1alpha1.GraphqlSource, opts v1.UpdateOptions) (result *v1alpha1.GraphqlSource, err error) {
	result = &v1alpha1.GraphqlSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("graphqlsources").
		Name(graphqlSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(graphqlSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the graphqlSource and deletes it. Returns an error if one occurs.
func (c *graphqlSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("graphqlsources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *graphqlSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("graphqlsources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched graphqlSource.
func (c *graphqlSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GraphqlSource, err error) {
	result = &v1alpha1.GraphqlSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("graphqlsources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
