name: Gateway
on:
  pull_request:
    paths:
      - 'gateway/**'  
    branches:
      - main
      - 'v**'
jobs:
  gateway:
    name: Build and test gateway
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: cd gateway && go build -v .
      - name: Test
        run: cd gateway && go test ./...
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.26.0
          sudo cp ./bin/golangci-lint $GOPATH/bin/
          cd gateway && golangci-lint run -E golint --exclude-use-default=false --timeout 600s ./...
